---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Install Packages
      package:
        name:
          - htop
          - screen
          - python3-psutil

    - name: Copy Wallpaper
      copy:
        src: stow/root/gnome-backgrounds/usr/share/backgrounds/gnome/bell_heather_spekes_mill.jpg
        dest: /usr/share/backgrounds/
        owner: root
        group: root

    - name: Set Wallpaper
      become_user: pi
      dconf:
        key: "/org/gnome/desktop/background/picture-uri"
        value: "'file:///usr/share/backgrounds/bell_heather_spekes_mill.jpg'"

    - name: Set Wallpaper Postition
      become_user: pi
      dconf:
        key: "/org/gnome/dekstop/background/picture-options"
        value: "'zoom'"

    - name: copy .zshrc
      copy:
        src: stow/home/core-zsh/.zshrc
        dest: /home/pi/
        owner: pi
        group: pi
