---
gnome_packages:
  - aspell-en
  - bluez-utils
  - celluloid
  - cups
  - ddcutil
  - discord
  - displaycal
  - dmidecode
  - dolphin-emu
  - firefox
  - flatpak
  - fwupd
  - geary
  - gedit-plugins
  - gimp
  - gnome
  - gnome-packagekit
  - gnome-software-packagekit-plugin
  - gnome-todo
  - gnome-tweaks
  - gparted
  - gvim
  - hunspell-en_gb
  - ibus
  - jdk-openjdk
  - lib32-systemd
  - libgit2-glib
  - libpipewire02
  - libreoffice-fresh
  - marker
  - mathjax2
  - networkmanager
  - networkmanager-openvpn
  - noto-fonts-cjk
  - noto-fonts-extra
  - ntfs-3g
  - nuspell
  - pandoc
  - plantuml
  - steam
  - telegram-desktop
  - texlive-core
  - ttf-liberation
  - zathura-pdf-mupdf

aur_gnome_packages:
  - chrome-gnome-shell
  - etcher-bin
  - pulseaudio-modules-bt

flatpak_gnome_packages:
  - com.spotify.Client
  - com.microsoft.Teams
  - us.zoom.Zoom

gnome_dconf:
  - key: "/com/github/fabiocolacio/marker/preferences/editor/auto-indent"
    value: "true"
  - key: "/com/github/fabiocolacio/marker/preferences/editor/enable-syntax-theme"
    value: "true"
  - key: "/com/github/fabiocolacio/marker/preferences/editor/spell-check"
    value: "true"
  - key: "/com/github/fabiocolacio/marker/preferences/editor/spell-check-lang"
    value: "'en_GB'"
  - key: "/com/github/fabiocolacio/marker/preferences/editor/syntax-theme"
    value: "'cobalt'"
  - key: "/com/github/fabiocolacio/marker/preferences/editor/wrap-text"
    value: "false"
  - key: "/com/github/fabiocolacio/marker/preferences/preview/css-theme"
    value: "'GitHub2.css'"
  - key: "/com/github/fabiocolacio/marker/preferences/preview/highlight-theme"
    value: "'tomorrow-night-blue'"
  - key: "/com/github/fabiocolacio/marker/preferences/preview/highlight-toggle"
    value: "true"
  - key: "/com/github/fabiocolacio/marker/preferences/preview/math-backend"
    value: "'MathJax'"
  - key: "/io/github/celluloid-player/celluloid/mpv-options"
    value: "'hwdec=auto'"
  - key: "/io/github/celluloid-player/celluloid/settings-migrated"
    value: "true"
  - key: "/org/gnome/desktop/app-folders/folder-children"
    value: "['Utilities', 'YaST', '64e83bb5-0b87-4161-8787-87239ba031ff', '8092f27f-6557-443a-9f0e-25022662f6b8', 'feb8e1e1-66b3-43ef-b13b-a5fef71e44c0']"
  - key: "/org/gnome/desktop/app-folders/folders/64e83bb5-0b87-4161-8787-87239ba031ff/apps"
    value: "['nm-connection-editor.desktop', 'bssh.desktop', 'bvnc.desktop', 'avahi-discover.desktop', 'calf.desktop', 'cmake-gui.desktop', 'ca.desrt.dconf-editor.desktop', 'gvim.desktop', 'lstopo.desktop', 'gtk-lshw.desktop', 'cups.desktop', 'mpv.desktop', 'jconsole-java-openjdk.desktop', 'jshell-java-openjdk.desktop', 'org.gnome.PackageUpdater.desktop', 'org.gnome.Packages.desktop', 'qv4l2.desktop', 'qvidcap.desktop', 'vim.desktop', 'xdvi.desktop']"
  - key: "/org/gnome/desktop/app-folders/folders/64e83bb5-0b87-4161-8787-87239ba031ff/name"
    value: "'Tools'"
  - key: "/org/gnome/desktop/app-folders/folders/64e83bb5-0b87-4161-8787-87239ba031ff/translate"
    value: "false"
  - key: "/org/gnome/desktop/app-folders/folders/8092f27f-6557-443a-9f0e-25022662f6b8/apps"
    value: "['libreoffice-startcenter.desktop', 'libreoffice-base.desktop', 'libreoffice-calc.desktop', 'libreoffice-draw.desktop', 'libreoffice-impress.desktop', 'libreoffice-math.desktop', 'libreoffice-writer.desktop']"
  - key: "/org/gnome/desktop/app-folders/folders/8092f27f-6557-443a-9f0e-25022662f6b8/name"
    value: "'Office'"
  - key: "/org/gnome/desktop/app-folders/folders/Utilities/apps"
    value: "['org.gnome.FileRoller.desktop', 'balena-etcher-electron.desktop', 'org.gnome.Books.desktop', 'org.gnome.Boxes.desktop', 'org.gnome.Characters.desktop', 'org.gnome.Cheese.desktop', 'chromium.desktop', 'org.gnome.Contacts.desktop', 'org.gnome.DiskUtility.desktop', 'org.gnome.baobab.desktop', 'org.gnome.Documents.desktop', 'simple-scan.desktop', 'org.gnome.Evince.desktop', 'dolphin-emu.desktop', 'org.gnome.font-viewer.desktop', 'gimp.desktop', 'gparted.desktop', 'yelp.desktop', 'org.gnome.Logs.desktop', 'org.gnome.Music.desktop', 'org.gnome.Photos.desktop', 'piavpn.desktop', 'com.github.wwmm.pulseeffects.desktop', 'org.gnome.Screenshot.desktop', 'transmission-gtk.desktop', 'org.gnome.tweaks.desktop', 'org.gnome.Totem.desktop', 'org.videolan.VLC.desktop', 'org.gnome.Epiphany.desktop', 'org.pwmt.zathura.desktop']"
  - key: "/org/gnome/desktop/app-folders/folders/Utilities/categories"
    value: "['X-GNOME-Utilities']"
  - key: "/org/gnome/desktop/app-folders/folders/Utilities/excluded-apps"
    value: "['nm-connection-editor.desktop', 'org.gnome.eog.desktop']"
  - key: "/org/gnome/desktop/app-folders/folders/Utilities/name"
    value: "'X-GNOME-Utilities.directory'"
  - key: "/org/gnome/desktop/app-folders/folders/Utilities/translate"
    value: "true"
  - key: "/org/gnome/desktop/app-folders/folders/YaST/categories"
    value: "['X-SuSE-YaST']"
  - key: "/org/gnome/desktop/app-folders/folders/YaST/name"
    value: "'suse-yast.directory'"
  - key: "/org/gnome/desktop/app-folders/folders/YaST/translate"
    value: "true"
  - key: "/org/gnome/desktop/app-folders/folders/feb8e1e1-66b3-43ef-b13b-a5fef71e44c0/apps"
    value: "['displaycal-3dlut-maker.desktop', 'displaycal-curve-viewer.desktop', 'displaycal.desktop', 'displaycal-profile-info.desktop', 'displaycal-apply-profiles.desktop', 'displaycal-scripting-client.desktop', 'displaycal-synthprofile.desktop', 'displaycal-testchart-editor.desktop', 'displaycal-vrml-to-x3d-converter.desktop']"
  - key: "/org/gnome/desktop/app-folders/folders/feb8e1e1-66b3-43ef-b13b-a5fef71e44c0/name"
    value: "'Calibration'"
  - key: "/org/gnome/desktop/app-folders/folders/feb8e1e1-66b3-43ef-b13b-a5fef71e44c0/translate"
    value: "false"
  - key: "/org/gnome/desktop/background/color-shading-type"
    value: "'solid'"
  - key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"
  - key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/gnome/bell_heather_spekes_mill.jpg'"
  - key: "/org/gnome/desktop/background/primary-color"
    value: "'#000000000000'"
    key: "/org/gnome/desktop/background/secondary-color"
    value: "'#000000000000'"
  - key: "/org/gnome/desktop/calendar/show-weekdate"
    value: "true"
  - key: "/org/gnome/desktop/datetime/automatic-timezone"
    value: "true"
  - key: "/org/gnome/desktop/input-sources/per-window"
    value: "false"
  - key: "/org/gnome/desktop/input-sources/sources"
    value: |-
      [('xkb', 'gb')]
  - key: "/org/gnome/desktop/input-sources/xkb-options"
    value: "['lv3:ralt_switch', 'compose:ralt']"
  - key: "/org/gnome/desktop/interface/clock-format"
    value: "'12h'"
  - key: "/org/gnome/desktop/interface/clock-show-weekday"
    value: "true"
  - key: "/org/gnome/desktop/interface/show-battery-percentage"
    value: "true"
  - key: "/org/gnome/desktop/peripherals/mouse/accel-profile"
    value: "'flat'"
  - key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
    value: "true"
  - key: "/org/gnome/desktop/peripherals/touchpad/two-finger-scrolling-enabled"
    value: "true"
  - key: "/org/gnome/desktop/screensaver/picture-options"
    value: "'zoom'"
  - key: "/org/gnome/desktop/screensaver/picture-uri"
    value: "'file:///home/ben/.local/share/backgrounds/2021-04-03-15-55-35-DSC_0015.jpg'"
  - key: "/org/gnome/desktop/sound/allow-volume-above-100-percent"
    value: "false"
  - key: "/org/gnome/desktop/wm/keybindings/switch-applications"
    value: "['<Super>Tab']"
  - key: "/org/gnome/desktop/wm/keybindings/switch-applications-backward"
    value: "['<Shift><Super>Tab']"
  - key: "/org/gnome/desktop/wm/keybindings/switch-windows"
    value: "['<Alt>Tab']"
  - key: "/org/gnome/desktop/wm/keybindings/switch-windows-backward"
    value: "['<Shift><Alt>Tab']"
  - key: "/org/gnome/desktop/wm/keybindings/toggle-fullscreen"
    value: "['<Alt>Return']"
  - key: "/org/gnome/desktop/wm/preferences/button-layout"
    value: "'appmenu:minimize,maximize,close'"
  - key: "/org/gnome/desktop/wm/preferences/resize-with-right-button"
    value: "true"
  - key: "/org/gnome/gedit/preferences/editor/display-right-margin"
    value: "true"
  - key: "/org/gnome/gedit/preferences/editor/scheme"
    value: "'cobalt'"
  - key: "/org/gnome/gedit/preferences/editor/tabs-size"
    value: "uint32 4"
  - key: "/org/gnome/gedit/preferences/editor/wrap-last-split-mode"
    value: "'word'"
  - key: "/org/gnome/gnome-system-monitor/current-tab"
    value: "'processes'"
  - key: "/org/gnome/gnome-system-monitor/maximized"
    value: "false"
  - key: "/org/gnome/gnome-system-monitor/network-in-bits"
    value: "true"
  - key: "/org/gnome/gnome-system-monitor/network-total-in-bits"
    value: "false"
  - key: "/org/gnome/gnome-system-monitor/network-total-unit"
    value: "true"
  - key: "/org/gnome/gnome-system-monitor/show-dependencies"
    value: "false"
  - key: "/org/gnome/gnome-system-monitor/show-whose-processes"
    value: "'all'"
  - key: "/org/gnome/gnome-system-monitor/window-state"
    value: "(668, 950, 26, 23)"
  - key: "/org/gnome/gnome-system-monitor/proctree/col-1-visible"
    value: "false"
  - key: "/org/gnome/gnome-system-monitor/proctree/col-1-width"
    value: "98"
  - key: "/org/gnome/gnome-system-monitor/proctree/col-22-visible"
    value: "false"
  - key: "/org/gnome/gnome-system-monitor/proctree/col-22-width"
    value: "100"
  - key: "/org/gnome/gnome-system-monitor/proctree/col-23-visible"
    value: "false"
  - key: "/org/gnome/gnome-system-monitor/proctree/col-23-width"
    value: "100"
  - key: "/org/gnome/gnome-system-monitor/proctree/col-26-visible"
    value: "false"
  - key: "/org/gnome/gnome-system-monitor/proctree/col-26-width"
    value: "100"
  - key: "/org/gnome/gnome-system-monitor/proctree/columns-order"
    value: "[0, 1, 2, 3, 4, 6, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]"
  - key: "/org/gnome/gnome-system-monitor/proctree/sort-col"
    value: "8"
  - key: "/org/gnome/gnome-system-monitor/proctree/sort-order"
    value: "0"
  - key: "/org/gnome/nautilus/list-view/default-column-order"
    value: "['name', 'size', 'type', 'detailed_type', 'owner', 'group', 'permissions', 'where', 'date_modified', 'date_modified_with_time', 'date_accessed', 'date_created', 'recency', 'starred']"
  - key: "/org/gnome/nautilus/list-view/default-visible-columns"
    value: "['name', 'detailed_type', 'size', 'date_modified']"
  - key: "/org/gnome/nautilus/list-view/default-zoom-level"
    value: "'small'"
  - key: "/org/gnome/nautilus/list-view/use-tree-view"
    value: "true"
  - key: "/org/gnome/nautilus/preferences/default-folder-viewer"
    value: "'list-view'"
  - key: "/org/gnome/nautilus/preferences/recursive-search"
    value: "'always'"
  - key: "/org/gnome/nautilus/preferences/search-filter-time-type"
    value: "'last_modified'"
  - key: "/org/gnome/nautilus/preferences/search-view"
    value: "'list-view'"
  - key: "/org/gnome/nautilus/preferences/show-create-link"
    value: "true"
  - key: "/org/gnome/nautilus/preferences/show-directory-item-counts"
    value: "'always'"
  - key: "/org/gnome/nautilus/preferences/show-image-thumbnails"
    value: "'always'"
  - key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
    value: "true"
  - key: "/org/gnome/settings-daemon/plugins/color/night-light-temperature"
    value: "uint32 3700"
  - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
  - key: "/org/gnome/settings-daemon/plugins/media-keys/next"
    value: "['<Alt>l']"
  - key: "/org/gnome/settings-daemon/plugins/media-keys/play"
    value: "['<Alt>j']"
  - key: "/org/gnome/settings-daemon/plugins/media-keys/previous"
    value: "['<Alt>h']"
  - key: "/org/gnome/settings-daemon/plugins/media-keys/stop"
    value: "['<Alt>k']"
  - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding"
    value: "'<Super>t'"
  - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command"
    value: "'gnome-terminal'"
  - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name"
    value: "'Terminal'"
  - key: "/org/gnome/shell/app-picker-layout"
    value: "[{'org.gnome.Calculator.desktop': <{'position': <0>}>, 'org.gnome.Calendar.desktop': <{'position': <1>}>, 'feb8e1e1-66b3-43ef-b13b-a5fef71e44c0': <{'position': <2>}>, 'io.github.celluloid_player.Celluloid.desktop': <{'position': <3>}>, 'org.gnome.clocks.desktop': <{'position': <4>}>, 'discord.desktop': <{'position': <5>}>, 'org.gnome.Extensions.desktop': <{'position': <6>}>, 'org.gnome.eog.desktop': <{'position': <7>}>, 'org.gnome.Maps.desktop': <{'position': <8>}>, 'com.github.fabiocolacio.marker.desktop': <{'position': <9>}>, 'com.microsoft.Teams.desktop': <{'position': <10>}>, '8092f27f-6557-443a-9f0e-25022662f6b8': <{'position': <11>}>, 'gnome-control-center.desktop': <{'position': <12>}>, 'org.gnome.Software.desktop': <{'position': <13>}>, 'steam.desktop': <{'position': <14>}>, 'gnome-system-monitor.desktop': <{'position': <15>}>, 'telegramdesktop.desktop': <{'position': <16>}>, 'org.gnome.Terminal.desktop': <{'position': <17>}>, 'org.gnome.gedit.desktop': <{'position': <18>}>, 'org.gnome.Todo.desktop': <{'position': <19>}>, '64e83bb5-0b87-4161-8787-87239ba031ff': <{'position': <20>}>, 'Utilities': <{'position': <21>}>, 'org.gnome.Weather.desktop': <{'position': <22>}>, 'us.zoom.Zoom.desktop': <{'position': <23>}>}]"
  - key: "/org/gnome/shell/disable-user-extensions"
    value: "false"
  - key: "/org/gnome/shell/disabled-extensions"
    value: "['launch-new-instance@gnome-shell-extensions.gcampax.github.com', 'status-area-horizontal-spacing@mathematical.coffee.gmail.com']"
  - key: "/org/gnome/shell/enabled-extensions"
    value: "['dash-to-dock@micxgx.gmail.com', 'caffeine@patapon.info', 'sound-output-device-chooser@kgshank.net', 'TopIcons@phocean.net', 'gTile@vibou', 'bluetooth-quick-connect@bjarosze.gmail.com', 'espresso@coadmunkee.github.com', 'tiling-assistant@leleat-on-github', 'nightthemeswitcher@romainvigier.fr', 'trayIconsReloaded@selfmade.pl', 'Vitals@CoreCoding.com', 'quick-app-launcher@leleat-on-github', 'no-overview@fthx', 'display-brightness-ddcutil@themightydeity.github.com']"
  - key: "/org/gnome/shell/favorite-apps"
    value: "['firefox.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Geary.desktop', 'com.spotify.Client.desktop']"
  - key: "/org/gnome/shell/extensions/bluetooth-quick-connect/keep-menu-on-toggle"
    value: "true"
  - key: "/org/gnome/shell/extensions/bluetooth-quick-connect/refresh-button-on"
    value: "false"
  - key: "/org/gnome/shell/extensions/display-brightness-ddcutil/show-all-slider"
    value: "true"
  - key: "/org/gnome/shell/extensions/display-brightness-ddcutil/show-value-label"
    value: "true"
  - key: "/org/gnome/shell/extensions/espresso/show-notifications"
    value: "false"
  - key: "/org/gnome/shell/extensions/gtile/show-icon"
    value: "false"
  - key: "/org/gnome/shell/extensions/nightthemeswitcher/settings-version"
    value: "1"
  - key: "/org/gnome/shell/extensions/nightthemeswitcher/time/always-enable-ondemand"
    value: "true"
  - key: "/org/gnome/shell/extensions/nightthemeswitcher/time/nightlight-follow-disable"
    value: "true"
  - key: "/org/gnome/shell/extensions/nightthemeswitcher/time/nightthemeswitcher-ondemand-keybinding"
    value: "['<Super>d']"
  - key: "/org/gnome/shell/extensions/nightthemeswitcher/time/ondemand-button-placement"
    value: "'none'"
  - key: "/org/gnome/shell/extensions/nightthemeswitcher/time/ondemand-time"
    value: "'day'"
  - key: "/org/gnome/shell/extensions/nightthemeswitcher/time/time-source"
    value: "'nightlight'"
  - key: "/org/gnome/shell/extensions/sound-output-device-chooser/expand-volume-menu"
    value: "true"
  - key: "/org/gnome/shell/weather/automatic-location"
    value: "true"
  - key: "/org/gnome/shell/world-clocks/locations"
    value: "@av []"
  - key: "/org/gnome/software/first-run"
    value: "false"
  - key: "/org/gnome/system/location/enabled"
    value: "true"
  - key: "/org/gnome/terminal/legacy/profiles:/default"
    value: "'749bd384-6325-4410-b868-d40e7cecf7cf'"
  - key: "/org/gnome/terminal/legacy/profiles:/list"
    value: "['749bd384-6325-4410-b868-d40e7cecf7cf']"
  - key: "/org/gnome/terminal/legacy/profiles:/:749bd384-6325-4410-b868-d40e7cecf7cf/allow-bold"
    value: "true"
  - key: "/org/gnome/terminal/legacy/profiles:/:749bd384-6325-4410-b868-d40e7cecf7cf/background-color"
    value: "'#131327273838'"
  - key: "/org/gnome/terminal/legacy/profiles:/:749bd384-6325-4410-b868-d40e7cecf7cf/bold-color"
    value: "'#ffffffffffff'"
  - key: "/org/gnome/terminal/legacy/profiles:/:749bd384-6325-4410-b868-d40e7cecf7cf/bold-color-same-as-fg"
    value: "true"
  - key: "/org/gnome/terminal/legacy/profiles:/:749bd384-6325-4410-b868-d40e7cecf7cf/cursor-background-color"
    value: "'#ffffffffffff'"
  - key: "/org/gnome/terminal/legacy/profiles:/:749bd384-6325-4410-b868-d40e7cecf7cf/cursor-colors-set"
    value: "true"
  - key: "/org/gnome/terminal/legacy/profiles:/:749bd384-6325-4410-b868-d40e7cecf7cf/cursor-foreground-color"
    value: "'#131327273838'"
  - key: "/org/gnome/terminal/legacy/profiles:/:749bd384-6325-4410-b868-d40e7cecf7cf/default-size-columns"
    value: "132"
  - key: "/org/gnome/terminal/legacy/profiles:/:749bd384-6325-4410-b868-d40e7cecf7cf/default-size-rows"
    value: "43"
  - key: "/org/gnome/terminal/legacy/profiles:/:749bd384-6325-4410-b868-d40e7cecf7cf/foreground-color"
    value: "'#ffffffffffff'"
  - key: "/org/gnome/terminal/legacy/profiles:/:749bd384-6325-4410-b868-d40e7cecf7cf/palette"
    value: "['#000000000000', '#ffff00000000', '#3838dede2121', '#ffffe5e50a0a', '#14146060d2d2', '#ffff00005d5d', '#0000bbbbbbbb', '#bbbbbbbbbbbb', '#555555555555', '#f4f40e0e1717', '#3b3bd0d01d1d', '#ededc8c80909', '#55555555ffff', '#ffff5555ffff', '#6a6ae3e3fafa', '#ffffffffffff']"
  - key: "/org/gnome/terminal/legacy/profiles:/:749bd384-6325-4410-b868-d40e7cecf7cf/use-theme-background"
    value: "false"
  - key: "/org/gnome/terminal/legacy/profiles:/:749bd384-6325-4410-b868-d40e7cecf7cf/use-theme-colors"
    value: "false"
  - key: "/org/gnome/terminal/legacy/profiles:/:749bd384-6325-4410-b868-d40e7cecf7cf/use-theme-transparency"
    value: "false"
  - key: "/org/gnome/terminal/legacy/profiles:/:749bd384-6325-4410-b868-d40e7cecf7cf/visible-name"
    value: "'Cobalt 2'"
  - key: "/org/gnome/tweaks/show-extensions-notice"
    value: "false"
  - key: "/org/gtk/settings/file-chooser/clock-format"
    value: "'12h'"
  - key: "/org/gtk/settings/file-chooser/date-format"
    value: "'regular'"
  - key: "/org/gtk/settings/file-chooser/location-mode"
    value: "'path-bar'"
  - key: "/org/gtk/settings/file-chooser/show-size-column"
    value: "true"
  - key: "/org/gtk/settings/file-chooser/show-type-column"
    value: "true"
  - key: "/org/gtk/settings/file-chooser/sort-column"
    value: "'name'"
  - key: "/org/gtk/settings/file-chooser/sort-directories-first"
    value: "true"
  - key: "/org/gtk/settings/file-chooser/sort-order"
    value: "'descending'"
  - key: "/org/gtk/settings/file-chooser/type-format"
    value: "'category'"
