---
- name: 'installing laptop packages'
  community.general.pacman:
    executable: 'yay'
    extra_args: '--removemake'
    name: '{{ laptop_packages  + aur_laptop_packages}}'
    state: 'present'
    update_cache: true
