---
- name: 'installing laptop packages'
  community.general.pacman:
    executable: 'yay'
    extra_args: '--removemake --asexplicit'
    name: '{{ laptop_packages }}'
    state: 'present'
    update_cache: true

- name: 'set laptop packages to explicitly installed'
  ansible.builtin.shell:
    cmd: 'yay -D --asexplicit {{ laptop_packages | join(" ") }} $(yay -Sgq {{ laptop_packages | join(" ") }})'
  changed_when: false
  failed_when: false
