---
- include_tasks: 'arch.yml'
  when: ansible_facts['os_family'] == 'Archlinux'

- include_tasks: 'debian.yml'
  when: ansible_facts['os_family'] == 'Debian'

- name: 'removing lsp-plugins desktop entries'
  ansible.builtin.shell:
    cmd: |
      echo '[Desktop Entry] Hidden=true' > /tmp/1
      find /usr -name "*lsp_plug*desktop" 2>/dev/null | cut -f 5 -d '/' | xargs -I {} cp '/tmp/1' "~/.local/share/applications/{}"
    creates: '~/.local/share/applications/*lsp_plug*desktop'

- name: 'installing laptop dotfiles for user'
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '~/'
    directory_mode: 0755
    mode: 0644
    group: 1000
    owner: 1000
  loop:
    - 'user/pulseeffects/'

- name: 'installing laptop dotfiles for root'
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '/'
    directory_mode: 0755
    mode: 0644
    group: 0
    owner: 0
  loop:
    - 'root/egpu/'
    - 'root/mkinitcpio/'
  become: true
