---
- include_tasks: 'arch.yml'
  when: ansible_facts['os_family'] == 'Archlinux'

- include_tasks: 'debian.yml'
  when: ansible_facts['os_family'] == 'Debian'

- name: 'checking for stock mkinitcpio'
  ansible.builtin.lineinfile:
    name: '/etc/mkinitcpio.conf'
    line: 'HOOKS=(systemd autodetect modconf block filesystems fsck)'
    state: 'present'
  check_mode: true
  register: 'mkinitcpio'

- name: 'installing laptop dotfiles for root'
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '/'
    directory_mode: 0755
    mode: 0644
    group: '0'
    owner: '0'
  loop:
    - 'root/egpu/'
    - 'root/mkinitcpio/'
  become: true

- name: 'building boot image with mkinitcpio'
  ansible.builtin.command:
    cmd: 'mkinitcpio -P'
  become: true
  when: 'mkinitcpio.changed'

- name: 'configuring boot parameters'
  ansible.builtin.replace:
    path: '/boot/loader/entries/arch.conf'
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
  loop:
    - regexp: '^(linux.*\n)(.*initramfs.*)$'
      replace: '\g<1>initrd\t/intel-ucode.img\n\g<2>'
    - regexp: '^(options\sroot=\".*\" rw)$'
      replace: '\g<1> quiet i915.enable_guc=2 i915.enable_psr=0 i8042.dumbkbd'
  become: true

- name: 'enabling laptop services'
  ansible.builtin.service:
    enabled: true
    name: '{{ item }}'
  loop:
    - 'power-profiles-daemon'
  become: true
