---
- name: Installing Laptop Dotfiles for user
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "~/"
  loop:
    - "user/pulseeffects/"

- name: Installing Laptop Dotfiles for root
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/"
  loop:
    - "root/egpu/"
    - "root/mkinitcpio/"

- include_tasks: arch.yml
  when: ansible_facts['os_family'] == 'Archlinux'

- include_tasks: debian.yml
  when: ansible_facts['os_family'] == 'Debian'

- name: Removing lsp-plugins Desktop Entries
  ansible.builtin.shell:
    cmd: |
      echo "[Desktop Entry] Hidden=true" > /tmp/1
      find /usr -name "*lsp_plug*desktop" 2>/dev/null | cut -f 5 -d '/' | xargs -I {} cp /tmp/1 ~/.local/share/applications/{}
    creates: ~/.local/share/applications/*lsp_plug*desktop
