---
- name: 'installing gnome packages'
  community.general.pacman:
    executable: 'yay'
    extra_args: '--removemake --useask --ask=4'
    name: '{{ gnome_packages + aur_gnome_packages }}'
    state: 'present'
    update_cache: true

- name: 'set gnome packages to explicitly installed'
  ansible.builtin.shell:
    cmd: 'yay -D --asexplicit {{ (gnome_packages + aur_gnome_packages) | join(" ") }} $(yay -Sgq {{ (gnome_packages + aur_gnome_packages) | join(" ") }})'
  changed_when: false
  failed_when: false
