---
- name: 'installing gnome packages'
  community.general.pacman:
    executable: 'yay'
    extra_args: '--removemake --useask --ask=4'
    name: '{{ gnome_packages + aur_gnome_packages }}'
    state: 'present'
    update_cache: true
