---
- include_tasks: arch.yml
  when: ansible_facts['os_family'] == 'Archlinux'

- include_tasks: debian.yml
  when: ansible_facts['os_family'] == 'Debian'

- name: Installing Flatpack Packages
  community.general.flatpak:
    name: "{{ flatpak_gnome_packages }}"
    state: present

- name: Installing Gnome Dotfiles for user
  ansible.posix.synchronize:
    src: "{{ item }}"
    dest: "~/"
    recursive: yes
    archive: no
    checksum: yes
  loop:
    - "user/extensions/"
    - "user/templates/"

- name: Installing Gnome Dotfiles for root
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/"
  loop:
    - "root/backgrounds/"
    - "root/environment/"
    - "root/marker-mermaid/"
    - "root/pulseaudio/"

- name: Installing Geoclue Fix
  become: true
  ansible.builtin.replace:
    path: /etc/geoclue/geoclue.conf
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - regexp: |
        #url=https://location\.services\.mozilla\.com/v1/geolocate\?key=YOUR_KEY
      replace: |
        url=https://location.services.mozilla.com/v1/geolocate?key=geoclue
    - regexp: |
        #submission-url=https://location\.services\.mozilla\.com/v1/submit\?key=YOUR_KEY
      replace: |
        submission-url=https://location.services.mozilla.com/v1/submit?key=geoclue

- name: Configuring dconf
  community.general.dconf:
    key: '{{ item.key }}'
    value: '{{ item.value | string }}'
    state: present
  with_items: '{{ gnome_dconf }}'

- name: Logging into Accounts
  ansible.builtin.shell:
    cmd: gnome-control-center online-accounts
    creates: ~/.config/goa-1.0/accounts.conf
