---
- include_tasks: 'arch.yml'
  when: ansible_facts['os_family'] == 'Archlinux'

- include_tasks: 'debian.yml'
  when: ansible_facts['os_family'] == 'Debian'

- name: 'installing flatpack packages'
  community.general.flatpak:
    name: '{{ flatpak_gnome_packages }}'
    state: 'present'

- name: 'installing gnome dotfiles for user'
  ansible.posix.synchronize:
    archive: false
    checksum: true
    src: '{{ item }}'
    dest: '~/'
    group: true
    owner: true
    perms: true
    recursive: true
  loop:
    - 'user/extensions/'
    - 'user/pulseeffects/'
    - 'user/templates/'
    - 'user/wine/'

- name: 'installing gnome dotfiles for root'
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '/'
    directory_mode: 0755
    mode: 0644
    group: 0
    owner: 0
  loop:
    - 'root/backgrounds/'
    - 'root/environment/'
    - 'root/marker-mermaid/'
    - 'root/pulseaudio/'
  become: true

- name: 'stopping wineserver'
  ansible.builtin.command:
    cmd: 'wineserver -k'
    creates: '~/.wine/drive_c/windows/Fonts/corefonts.installed'
  ignore_errors: true


- name: 'installing and configuring wine fonts'
  ansible.builtin.shell:
    cmd: |
      winetricks corefonts
      cat << EOF > /tmp/fontsmoothing
      REGEDIT4
      [HKEY_CURRENT_USER\Control Panel\Desktop]
      "FontSmoothing"="2"
      "FontSmoothingOrientation"=dword:00000001
      "FontSmoothingType"=dword:00000002
      "FontSmoothingGamma"=dword:00000578
      EOF
      WINE=${WINE:-wine} WINEPREFIX=${WINEPREFIX:-$HOME/.wine} $WINE regedit /tmp/fontsmoothing 2> /dev/null
    creates: '~/.wine/drive_c/windows/Fonts/corefonts.installed'

- name: 'installing geoclue fix'
  ansible.builtin.replace:
    path: '/etc/geoclue/geoclue.conf'
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
  loop:
    - regexp: '#url=https://location\.services\.mozilla\.com/v1/geolocate\?key=YOUR_KEY'
      replace: 'url=https://location.services.mozilla.com/v1/geolocate?key=geoclue'
    - regexp: 'submission-url=https://location\.services\.mozilla\.com/v1/submit\?key=YOUR_KEY'
      replace: 'submission-url=https://location.services.mozilla.com/v1/submit?key=geoclue'
  become: true

- name: 'configuring ddcutil permissions'
  ansible.builtin.copy:
    src: '/usr/share/ddcutil/data/45-ddcutil-i2c.rules'
    dest: '/etc/udev/rules.d'
    mode: 0644
    group: 0
    owner: 0
  become: true

- name: 'adding user to i2c group'
  ansible.builtin.user:
    append: true
    groups:
      - 'i2c'
    name: '{{ ansible_env.USER }}'
  become: true

- name: 'configuring dconf'
  community.general.dconf:
    key: '{{ item.key }}'
    value: '{{ item.value | string }}'
    state: 'present'
  with_items: '{{ gnome_dconf }}'

- name: 'enabling/starting gnome services'
  ansible.builtin.service:
    enabled: true
    name: '{{ item }}'
  loop:
    - 'NetworkManager'
    - 'bluetooth'
    - 'cups'
    - 'gdm'
  become: true
