---
- include_tasks: 'arch.yml'
  when: ansible_facts['os_family'] == 'Archlinux'

- include_tasks: 'debian.yml'
  when: ansible_facts['os_family'] == 'Debian'

- name: 'installing flatpack packages'
  community.general.flatpak:
    name: '{{ flatpak_gnome_packages }}'
    state: 'present'

- name: 'installing gnome dotfiles for user'
  ansible.posix.synchronize:
    archive: false
    checksum: true
    src: '{{ item }}'
    dest: '~/'
    group: true
    owner: true
    perms: true
    recursive: true
  loop:
    - 'user/extensions/'
    - 'user/templates/'

- name: 'installing gnome dotfiles for root'
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '/'
    directory_mode: 0755
    mode: 0644
    group: 0
    owner: 0
  loop:
    - 'root/backgrounds/'
    - 'root/environment/'
    - 'root/marker-mermaid/'
    - 'root/pulseaudio/'
  become: true

- name: 'installing geoclue fix'
  ansible.builtin.replace:
    path: '/etc/geoclue/geoclue.conf'
    regexp: '{{ item.regexp }}'
    replace: '{{ item.replace }}'
  loop:
    - regexp: '#url=https://location\.services\.mozilla\.com/v1/geolocate\?key=YOUR_KEY'
      replace: 'url=https://location.services.mozilla.com/v1/geolocate?key=geoclue'
    - regexp: 'submission-url=https://location\.services\.mozilla\.com/v1/submit\?key=YOUR_KEY'
      replace: 'submission-url=https://location.services.mozilla.com/v1/submit?key=geoclue'
  become: true

- name: 'configuring dconf'
  community.general.dconf:
    key: '{{ item.key }}'
    value: '{{ item.value | string }}'
    state: 'present'
  with_items: '{{ gnome_dconf }}'

- name: 'logging into accounts'
  ansible.builtin.command:
    cmd: 'gnome-control-center online-accounts'
    creates: '~/.config/goa-1.0/accounts.conf'
