---
- name: 'installing server packages'
  community.general.pacman:
    executable: 'yay'
    extra_args: '--removemake'
    name: '{{ server_packages  + aur_server_packages}}'
    state: 'present'
    update_cache: true
