---
- name: Set Pacman Config
  become: true
  ansible.builtin.replace:
    path: /etc/pacman.conf
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - {regexp: "#Color", replace: "Color"}
    - {regexp: "#ParallelDownloads", replace: "ParallelDownloads"}
    -
      regexp: |
        #\[multilib\]
        #Include = /etc/pacman.d/mirrorlist
      replace: |
        [multilib]
        Include = /etc/pacman.d/mirrorlist

- name: Gather Package Facts 
  ansible.builtin.package_facts:

- name: Installing AUR Dependancies
  become: true
  community.general.pacman:
    name: base-devel
    state: present
  when: "'yay' not in ansible_facts.packages"

- name: Installing yay
  ansible.builtin.shell:
    cmd: |
      cd ~
      git clone https://aur.archlinux.org/yay.git
      cd yay
      makepkg -si --noconfirm
      cd ~
      rm -rf yay
  when: "'yay' not in ansible_facts.packages"

- name: Updating Packages
  community.general.pacman:
    executable: yay
    update_cache: yes
    upgrade: yes

- name: Installing Common Packages
  community.general.pacman:
    executable: yay
    update_cache: yes
    name: "{{ common_packages + aur_common_packages }}"
    state: present

# - name: Removing unlisted packages
