---
- name: 'installing common packages'
  ansible.builtin.apt:
    name: '{{ debian_common_packages }}'
    state: 'present'
    update_cache: true
  become: true

- name: 'gather package facts'
  ansible.builtin.package_facts:

- name: 'installing glances via pip'
  ansible.builtin.pip:
    name: 'glances'
    state: 'present'
    umask: '0022'
  when: '"glances" not in ansible_facts.packages'
  become: true

- name: 'updating packages'
  ansible.builtin.apt:
    update_cache: true
    upgrade: 'dist'
  become: true

# - name: 'removing unlisted packages'

- name: 'copying ssh keys'
  ansible.builtin.copy:
    backup: true
    src: 'user/keys/'
    dest: '~/'
    directory_mode: 0755
    mode: 0400
    group: 1000
    owner: 1000

- name: 'check if ssh key is on keyring'
  ansible.builtin.shell:
    cmd: 'ssh-add -l || /bin/true'
  changed_when: false
  register: 'keys'

- name: 'adding ssh key to keyring'
  ansible.builtin.shell:
    cmd: |
      eval $(ssh-agent)
      ssh-add ~/.ssh/id_ed25519
  when: '"b.weston60@gmail.com" not in keys'
