---
- name: Test Internet and DNS on 8.8.8.8
  ansible.builtin.shell: ping -q -c 1 -W 1 google.com
  changed_when: false

- include_tasks: arch.yml
  when: ansible_facts['os_family'] == 'Archlinux'

- include_tasks: debian.yml
  when: ansible_facts['os_family'] == 'Debian'

- name: Setting Shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    shell: /usr/bin/zsh
  loop:
    - "{{ ansible_env.USER }}"
    - root

- name: Installing ohmyzsh for user
  ansible.builtin.shell:
    cmd: RUNZSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    creates: ~/.oh-my-zsh

- name: Installing ohmyzsh for root
  become: true
  ansible.builtin.shell:
    cmd: RUNZSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    creates: /root/.oh-my-zsh

- name: Installing Common Dotfiles for user
  ansible.builtin.copy:
    backup: true
    src: "{{ item }}"
    dest: "~/"
  loop:
    - "user/git/"
    - "user/vim/"
    - "user/zsh/"

- name: Installing Common Dotfiles for root
  become: true
  ansible.builtin.copy:
    backup: true
    src: "{{ item }}"
    dest: "/"
  loop:
    - "root/zsh/"

- name: Installing Geoclue Fix
  become: true
  ansible.builtin.replace:
    path: /etc/geoclue/geoclue.conf
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - regexp: |
        #url=https://location\.services\.mozilla\.com/v1/geolocate\?key=YOUR_KEY
      replace: |
        url=https://location.services.mozilla.com/v1/geolocate?key=geoclue
    - regexp: |
        #submission-url=https://location\.services\.mozilla\.com/v1/submit\?key=YOUR_KEY
      replace: |
        submission-url=https://location.services.mozilla.com/v1/submit?key=geoclue

- name: Installing/Updating vim-plug plugins
  ansible.builtin.shell:
    cmd: vim +PlugInstall +PlugUpdate +PlugClean! +PlugUpgrade +qall
  register: vimplug
  changed_when: "'already up-to-date' not in vimplug.stdout"
